{% set name = "smp" %}
{% set version = "0.1.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/IntelPython/smp/archive/v{{ version }}.tar.gz
  sha256: 15e5c80392c43696eb1f8785d153e0f9751a0da127e7c66a262fef10be413d45

build:
  number: 0
  noarch: python
  entry_points:
    - python-smp = smp:_main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - SMP
    - smp
  commands:
    - python-smp --help
    - python -m smp test

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  home: https://github.com/IntelPython/smp
  summary: a Static Multi-Processing module managing nested parallelism

extra:
  recipe-maintainers:
    - anton-malakhov
