travis:
  secure:
    BINSTAR_TOKEN: D9eGAgVvvP0TsqXrd9JRD9nWxLIUHjGSFQvwsP/zyBmsn7AB98Bz1l/4bt4PEW70gIDNkzoEJJoXs/qn30QE2vHjt9OWEM31cS/iKa+A6HIZ93/h+SqhR9TtzfOpgqE+N8nP+kvt082F4c/6Vswn95xgpgfkK4G95eCWZIthlb47y0lH+cXfG0g0aAjtubm4FFuLo5/V0M2AMQgwVKKp4RTUXNloiOf3B57XP13Dh0bM9EKCnjbd44W7sIuLE8hxEC5gV+mZ8DLf6ht8ZcEyRyaS4N67lmOfmMxZ+alxzyaK63ag3hrNj+GMTZ/+KP/DTwOK3D0O+1zTvnSwqObH+p5SDArpEL4KVNEMl8fVtbapWHY1OLQXPDLldnWlWzmuNLGX08RlOuaEpNNBt/9qzVYP7kYXyYswlWhlXa4QhfDX1UUI6Z4+CnvvNR1qAvBX5DCIl/a1XwsaSUV4ggefTNRIQ8GuVfORWC0+3gpCDBvNSdU/NQr2UlnZBTmG+vH4RtGMqPMs0K18AK4ECzbfGhkD0FzBcrJgx+clBkdZZnvpDv1Jo6FZdaT7voqpntt+zyLZhjfyJcneRI1tJ0HcJqVzE3KaGkXoXxOLVo9Wf7FG+N6qcBqo3QaDPdP1zQViMTTlnKl46+X6Y/33veH7H/pFvbzsK9BdEIbSlhw7umo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
