travis:
  secure:
    BINSTAR_TOKEN: FsaqkUZSMnar0W2y4Mu4sfI+8TWq49dZLKlr8BLOAI6mMCkS3N8cwue0pIacJDSK9LIe7a2QUI0GHT+ox2JmGcW0BodGcr+UKTcLk/d5wslEcSVPuGzeJ6NKt5Jy5m+nSy7LcVbYntJB5uWrstt6yZf8MB4LVyOc0qgF1IcNXR9FW7L6u2E8cvtkZuiyW6JkEiXFScx/dCbViTJUyiwS4kuOJyA8zNc5OAYJqSXbB1ZeX2PO4xfLTAzDO25MJXfibYuanFwhEPwNInINeNwqAkqaxXt8R94sFVb6LchZu6mV0KhmTAMytbhHytV31xwSWzp8vn7YfgCXYLaYCASzSRl+zivLOrDS7UihP9s0fqtPn3GhvF2rgF5RbeAM5pLZzhnRGp0nonLVyrqFloaI8WeB/8f+EqB6GV1XHGjl5VMr0gihsief+xFff/FCQucYZWp8HyC5oOfWXQUUGwurNSt+3j2V1glczYcT4dizNltj9mdkms+GI69k2QsBNuZV+lvkFke8oA5bzAnopqp2Nzn+d2t6w+UkGbsJdyJ5Sn5JFP34N/ptPosTIXJe2QnOdFOQ9SLlLy3KFjpvEFhZcMWu5VnnNwbesw/AUXlt1bM/EyL0kL3O6qUfr7EqBhVxe/iP2jpBiXwMoCxhZOlryNbb4peb5Y8G0JeAyT5G8uo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
